import re


class CodeFileParser:
    """
    Parses structured code generated by the
    Code Generator Agent.

    Expected format:

    FILE: path/to/file.py

    <START OF FILE>
    file contents
    <END OF FILE>
    """

    def parse(self, generated_output: str) -> dict:
        """
        Convert the generated output into a dictionary
        containing file paths and their contents.
        """

        pattern = (
            r"FILE:\s*(.+?)\s*"
            r"<START OF FILE>\s*"
            r"(.*?)"
            r"<END OF FILE>"
        )

        matches = re.findall(
            pattern,
            generated_output,
            re.DOTALL
        )

        files = {}

        for file_path, content in matches:

            file_path = file_path.strip()
            content = content.strip()

            if file_path:
                files[file_path] = content

        return files